title: Dongyue Chen's Homepage
page-top-title: Dongyue Chen
top-section-bg-text: Computer Science
home-subtitle: Dongyue Chen&ensp;|&ensp;陈东月
copyright-text: '&copy; Dongyue Chen 2023-2024. All Rights Reserved.'
